config/routes.rb
require 'resque/server'

JSASearch::Application.routes.draw do
  
  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end
  
  authenticate :user do
    mount Resque::Server.new, :at => "/manage/resque1653508570"
  end
  
  scope "/manage" do
    resources :admin_defaults, :only => [:index, :edit, :update]

    resources :email_attachments, :only => [:create, :destroy]

    resources :clients do
      member do
        get :check_facility        
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
            
      resources :contacts
      
      resources :facilities do
        collection do
          get :tokens
        end
      end      
    end
    
    resource :facilities, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :contacts, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :doc_templates

    resources :tasks do
      put :finish, :on => :member
    end

    resources :exports,         :only => [:index]
    resources :activities,      :only => [:index]
    
    resources :mass_messages,   :only => [:create]    
    resources :direct_messages, :only => [:new, :create]
    resources :quick_messages,  :only => [:new, :create]
    resources :share_files,     :only => [:new, :create]
    
    resources :import_items, :only => [:index, :create, :destroy]
        
    resources :attachments, :only => [:create, :destroy, :show, :edit, :update]
    
    resources :notes, :only => [:create, :destroy, :show]
    
    resources :employees do
      post :update_position, :on => :collection
    end
    
    resources :load_more, :only => [:index]
    
    resources :applicants, :only => [:create, :destroy, :update_status, :mass_create] do
      member do
        put :update_status
      end
      collection do
        post :mass_create
      end
    end

    resources :jobs do
      member do
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
      end
    end
    
    resources :candidates do
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
      resources :work_histories
      member do
        put :update_status
      end
      resources :resumes do
        get :generate, :on => :member
      end
    end
    
    resources :autocomplete, :only => [:clients, :jobs, :candidates, :zip_codes, :all] do
      collection do
        get :clients
        get :jobs
        get :candidates
        get :zip_codes
        get :all
      end
    end
    
    resources :tokens, :only => [:users, :users_with_email, :jobs, :contacts_with_email, :contacts, :us_states] do
      collection do
        get :users
        get :users_with_email
        get :jobs
        get :contacts        
        get :contacts_with_email
        get :us_states
      end
    end

  end

  resources :campaigns, :only => [:index]
  
  # resources :candidates,
  #           :only => [:new, :create],
  #           :controller => :public_candidates,
  #           :path_names => { :new => 'sign-up' },
  #           :as => 'public_candidates'
            
  # resources :clients,
  #           :only => [:new, :create],
  #           :controller => :public_clients,
  #           :path_names => { :new => 'sign-up'},
  #           :as => 'public_clients'
            
  resources :questions, :only => [:new, :create]
  resources :bios, :only => [:index, :show], :path => "executive-bios"

  resources :resume_submissions, :only => [:index, :new, :create], :path => 'resume-submissions'
  resources :job_requests, :only => [:index, :new, :create], :path => 'job-orders'

  match 'jobs' => 'public_jobs#index', :as => :public_jobs
  match 'jobs/:id' => 'public_jobs#show'
  resources :job_inquiries,
            :only => [:index, :new, :create],
            :path => 'jobs/:id/inquiries'
  
  match 'about' => "contents#about", :as => :about

  match 'newsletters' => "contents#newsletters", :as => :newsletters  
  
  match 'employers' => "contents#employers", :as => :employers
    match 'employers/healthcare' => "contents#healthcare", :as => :healthcare
    match 'employers/interim-staffing' => "contents#interim", :as => :interim_staffing
    match 'employers/consulting' => "contents#consulting", :as => :consulting
    match 'employers/finance-and-accounting' => "contents#finance", :as => :finance
    match 'employers/thanks' => "contents#client_thanks", :as => :client_thank_you
  
  match 'candidates' => "contents#candidates", :as => :about_candidates
    match 'candidates/career-advice' => "contents#advice", :as => :career_advice
    match 'candidates/resume-writing-services' => "contents#resume_services", :as => :resume_writing_services
    match 'candidates/thanks' => "contents#candidate_thanks", :as => :candidate_thank_you
  
  match 'contact' => "contents#contact", :as => :contact

  match 'manage/dashboard' => 'contents#dashboard'

  root :to => 'contents#home' 
  
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps

  field :author
  field :content
  field :email
  field :subject
  field :bcc_email
  field :recipients
  field :user_ids,    :type => Array, :default => []
  field :contact_ids, :type => Array, :default => []
  field :job_ids,     :type => Array, :default => []
  field :emailed,     :type => Boolean, :default => false

  attr_accessible :author, :content, :email, :user_tokens, :job_tokens, :contact_tokens, :user_ids, :contact_ids, :job_ids, :recipients, :email_attachment_id, :bcc_email, :subject

  attr_accessor  :email_attachment_id, :subject_required
  alias :subject_required? :subject_required

  index :updated_at

  validates :author, :presence => true
  validates :content, :presence => true
  validate :verify_multiple_emails
  validates :bcc_email, :email_format => true, :allow_nil => true, :allow_blank => true

  validates :subject, :presence => true, if: :subject_required?

  with_options :if => :all_ids_blank? do |note|
    note.validates :user_ids, :presence => { :message => "Please enter an email or include people" }
    note.validates :contact_ids, :presence => { :message => "Please enter an email or include people" }
    note.validates :job_ids, :presence => { :message => "Please enter an email or include people" }
    note.validates :email, :presence => { :message => "Please enter an email or include people" }
  end

  has_many :email_attachments, :dependent => :delete
  before_validation :strip_fields
  before_save :cache_recipients
  after_save  :associate_email_attachment_to_note

  # Virtual Attrs =============================================

  def cache_recipients
    unless recipients.present?
      if emailed?
        text = ""

        text << "#{email}, " if email.present?

        %w( contact user ).each do |a|
          klass = a.camelize.constantize
          parent_field = send("#{a}_ids")

          if parent_field.present?
            people_names = klass.where(:_id.in => parent_field).only(:id, :name, :emails)
            people_names.map { |p| text << "#{p.name}, " }
          end
        end
        self.recipients = text.chomp(", ").strip
      end
    end
  end

  def generic_emails
    email_array = []
    email_array = email.split(',')
    email_array = email_array.each {|x| x.strip! }
    email_array = email_array.delete_if {|x| x.blank? }
    email_array
  end

  def user_tokens

  end

  def user_tokens=(var)
    self.user_ids = var.split(',').map{|id| BSON::ObjectId(id)}
  end

  def job_tokens
  end

  def job_tokens=(var)
    self.job_ids = var.split(',').map{|id| BSON::ObjectId(id)}
  end

  def contact_tokens
  end

  def contact_tokens=(var)
    self.contact_ids = var.split(',').map{|id| BSON::ObjectId(id)}
  end

  def all_ids_blank?
    if user_ids.blank? && contact_ids.blank? && job_ids.blank? && email.blank?
      true
    else
      false
    end
  end

  private

  def verify_multiple_emails
    if email.present?
      email.split(',').each do |e|
        unless e.present? && e =~ /@/
          errors[:email] << "needs to be double checked"
          return
        end
      end
    end
  end

  def strip_fields
    self.email     = email.strip if email.present?
    self.bcc_email = bcc_email.strip if bcc_email.present?
  end

  def associate_email_attachment_to_note
    EmailAttachment.find(email_attachment_id).update_attribute(:note_id, id)  if email_attachment_id.present?
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_employee!
  before_filter :authenticate_admin!, :only => [:destroy]

  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    @note = Note.new(params[:note])
    @parent_name = params[:parent_name]
    @parent_klass = params[:parent_klass]

    if @note.save
      Activity.notify(current_user.name, current_user.id, 0, 6, @note.id, @parent_name, @parent_klass)
      respond_to do |format|
        flash[:notice] = "Note Successfully Added"
        format.html { redirect_to @parent  }
        format.js
      end
    else
      respond_to do |format|
        flash[:alert] = "Could Not Create Note. Please Try Again"
        format.html { redirect_to @parent }
        format.js {render 'shared/error'}
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      flash[:notice] = "Note Destroyed"
      format.html { redirect_to dashboard_path }
      format.js { render 'shared/destroy_success' }
    end
  end

end

app/views/notes/_form.html.haml
= hidden_field_tag :parent_name, parent.name
= hidden_field_tag :parent_klass, parent.class.name
.fields
  = f.hidden_field :author, :value => current_user.name
  .item
    = f.text_area :content, :class => "note_content", :placeholder => "Add a Note..."    
  %p.hint
    Press alt+ctrl+s to save
    
.fields.tokenSearch
  = f.label :user_tokens, "CC: Candidates, Clients, and Employees"
  .item.token_field
    - if controller.controller_name == "clients" || controller.controller_name == "candidates" || controller.controller_name == "employees"
      = f.text_field :user_tokens, "data-pre" => member_name_and_id_to_json(parent), "data-path" => users_tokens_path  
    - else
      = f.text_field :user_tokens, "data-pre" => "", "data-path" => users_tokens_path
      
.fields.tokenSearch
  = f.label :contact_tokens, "CC: Contacts"
  .item.token_field
    - if controller.controller_name == "contacts"
      = f.text_field :contact_tokens, "data-pre" => member_name_and_id_to_json(parent), "data-path" => contacts_tokens_path  
    - else
      = f.text_field :contact_tokens, "data-pre" => "", "data-path" => contacts_tokens_path

.fields.tokenSearch
  = f.label :job_tokens, "CC: Jobs"
  .item.token_field
    - if controller.controller_name == "jobs"
      = f.text_field :job_tokens, "data-pre" => member_name_and_id_to_json(parent), "data-path" => jobs_tokens_path  
    - else
      = f.text_field :job_tokens, "data-pre" => "", "data-path" => jobs_tokens_path
                  
.actions
  = f.submit "Add Note", :class => 'button', "data-disable-with" => "Saving . . ."

app/views/notes/_note.html.haml
%div{:class => "note_title", "data-id" => "#{note.id.to_s}"}
  %hgroup
    %h1
      %a{:href => "#"}
        = note.author
        %em= "wrote on #{l(note.created_at.in_time_zone(current_time_zone), :format => :note_archive).downcase}".html_safe
%div{:class => "ui-accordion-content", "data-id" => "#{note.id.to_s}"}
  - if note.emailed?
    %p
      %strong Emailed to:
      = note.recipients
  - if note.email_attachments.present? && note.email_attachments.first.attachments.present?
    %p
      %strong Emailed File:
      = link_to note.email_attachments.first.attachments.first[:misc_file],
                note.email_attachments.first.attachments.first.misc_file.url,
                :title => "Download file"
      
  = simple_format note.content
  - if admin?
    .links          
      = link_to "Delete", note_path(note), |
                          :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |

app/views/notes/_preview.html.haml
%div{"data-id" => "#{preview.id.to_s}"}
  %section.notePreview
    - if preview.emailed?
      %p
        %strong
          Emailed to:
        = preview.recipients

    - if preview.email_attachments.present? && preview.email_attachments.first.attachments.present?
      %p
        %strong Emailed File:
        = link_to preview.email_attachments.first.attachments.first[:misc_file],
                  preview.email_attachments.first.attachments.first.misc_file.url,
                  :title => "Download file"        
    = simple_format preview.content

  - if admin?
    .links          
      = link_to "Delete", note_path(preview), |
                          :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |

app/views/notes/create.js.erb
$('#flash').remove();
$("header#banner").after('<div id="flash"><div id="notice"><%= escape_javascript(flash.discard(:notice)) %></div></div>');

$("textarea#note_content").val("");

if ( ($("#accordionNotes").length) && ($(".contactPreview").length < 1) ) {
  $("#accordionNotes").prepend("<%= escape_javascript(render :partial => 'notes/note', :locals => {:note => @note, :parent => @parent}) %>");
  $("#accordionNotes").accordion("destroy");

  $("#accordionNotes").accordion({
    collapsible: true,
    header: "div.note_title",
    autoHeight: false    
  });  
}

if ($(".modal.closeAfterSuccess").length) {
  $(".modal.closeAfterSuccess").remove();
}

$("textarea#note_content").parent().find(".charactersLeft").text("320");

var flashMargin = ($(window).width() - $("#flash").width()) / 2; 
$("#flash").css({'left' : flashMargin+"px"});
$("#flash").delay(5000).fadeOut('slow', function() {$(this).remove();});

app/views/notes/show.js.erb
$(".modal").append("<%= escape_javascript(render :partial => 'notes/preview', :object => @note) %>").addClass("contactPreview");

$("#flash").remove();

$(".modal").dialog({
 width: 600,
 height: 400,
 title: "<%= escape_javascript(@note.author) %> wrote <%= time_ago_in_words(@note.created_at) %> ago",
 position: ['center',50],
 close: function(event, ui) {
   $(this).removeClass("contactPreview");
 }
});

$("a").blur();