config/routes.rb
require 'resque/server'

JSASearch::Application.routes.draw do
  
  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end
  
  authenticate :user do
    mount Resque::Server.new, :at => "/manage/resque1653508570"
  end
  
  scope "/manage" do
    resources :admin_defaults, :only => [:index, :edit, :update]

    resources :email_attachments, :only => [:create, :destroy]

    resources :clients do
      member do
        get :check_facility        
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
            
      resources :contacts
      
      resources :facilities do
        collection do
          get :tokens
        end
      end      
    end
    
    resource :facilities, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :contacts, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :doc_templates

    resources :tasks do
      put :finish, :on => :member
    end

    resources :exports,         :only => [:index]
    resources :activities,      :only => [:index]
    
    resources :mass_messages,   :only => [:create]    
    resources :direct_messages, :only => [:new, :create]
    resources :quick_messages,  :only => [:new, :create]
    resources :share_files,     :only => [:new, :create]
    
    resources :import_items, :only => [:index, :create, :destroy]
        
    resources :attachments, :only => [:create, :destroy, :show, :edit, :update]
    
    resources :notes, :only => [:create, :destroy, :show]
    
    resources :employees do
      post :update_position, :on => :collection
    end
    
    resources :load_more, :only => [:index]
    
    resources :applicants, :only => [:create, :destroy, :update_status, :mass_create] do
      member do
        put :update_status
      end
      collection do
        post :mass_create
      end
    end

    resources :jobs do
      member do
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
      end
    end
    
    resources :candidates do
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
      resources :work_histories
      member do
        put :update_status
      end
      resources :resumes do
        get :generate, :on => :member
      end
    end
    
    resources :autocomplete, :only => [:clients, :jobs, :candidates, :zip_codes, :all] do
      collection do
        get :clients
        get :jobs
        get :candidates
        get :zip_codes
        get :all
      end
    end
    
    resources :tokens, :only => [:users, :users_with_email, :jobs, :contacts_with_email, :contacts, :us_states] do
      collection do
        get :users
        get :users_with_email
        get :jobs
        get :contacts        
        get :contacts_with_email
        get :us_states
      end
    end

  end

  resources :campaigns, :only => [:index]
  
  # resources :candidates,
  #           :only => [:new, :create],
  #           :controller => :public_candidates,
  #           :path_names => { :new => 'sign-up' },
  #           :as => 'public_candidates'
            
  # resources :clients,
  #           :only => [:new, :create],
  #           :controller => :public_clients,
  #           :path_names => { :new => 'sign-up'},
  #           :as => 'public_clients'
            
  resources :questions, :only => [:new, :create]
  resources :bios, :only => [:index, :show], :path => "executive-bios"

  resources :resume_submissions, :only => [:index, :new, :create], :path => 'resume-submissions'
  resources :job_requests, :only => [:index, :new, :create], :path => 'job-orders'

  match 'jobs' => 'public_jobs#index', :as => :public_jobs
  match 'jobs/:id' => 'public_jobs#show'
  resources :job_inquiries,
            :only => [:index, :new, :create],
            :path => 'jobs/:id/inquiries'
  
  match 'about' => "contents#about", :as => :about

  match 'newsletters' => "contents#newsletters", :as => :newsletters  
  
  match 'employers' => "contents#employers", :as => :employers
    match 'employers/healthcare' => "contents#healthcare", :as => :healthcare
    match 'employers/interim-staffing' => "contents#interim", :as => :interim_staffing
    match 'employers/consulting' => "contents#consulting", :as => :consulting
    match 'employers/finance-and-accounting' => "contents#finance", :as => :finance
    match 'employers/thanks' => "contents#client_thanks", :as => :client_thank_you
  
  match 'candidates' => "contents#candidates", :as => :about_candidates
    match 'candidates/career-advice' => "contents#advice", :as => :career_advice
    match 'candidates/resume-writing-services' => "contents#resume_services", :as => :resume_writing_services
    match 'candidates/thanks' => "contents#candidate_thanks", :as => :candidate_thank_you
  
  match 'contact' => "contents#contact", :as => :contact

  match 'manage/dashboard' => 'contents#dashboard'

  root :to => 'contents#home' 
  
end

app/views/employee_notifications/notify_export.html.erb
<p>Dear <%= @employee.name.split(" ").first %>,</p>

<p>Attached is your <%= @klass.camelize %> Export.</p>

<p>
	Thanks,<br/>
	The Team at JSA Search, Inc.
</p>

<p>
------------------------------------------------------------<br/>
JSA Search, Inc. / 866-572-8326 / jsasearch.net<br/>
23120 Alicia Parkway Suite 110<br/>
Mission Viejo, CA 92692
</p>

app/views/employee_notifications/notify_job_inquiry.html.erb
<p>-----------------------------------------------------------------------</p>
<p>You have received a job inquiry from <%= @job_inquiry.name %>.</p>

<p>-----------------------------------------------------------------------</p>

<p>Job: <%= link_to @job.name,
										job_url(@job, :only_path => false),
										:title => "Visit the job page" %></p>

<p>
	Name: <%= @job_inquiry.try(:name) %>
</p>

<% if @candidate.present? %>
<p>
	Candidate: <%= link_to @candidate.name,
												 candidate_url(@candidate, :only_path => false),
												 :title => "Visit the candidate page" %>
</p>
<% end %>

<p><%= @job_inquiry.email_type.titleize %> Email: <%= @job_inquiry.email_address %></p>

<p>Title: <%= @job_inquiry.title %></p>

<p>Company: <%= @job_inquiry.company %></p>

<p><%= @job_inquiry.phone_type.titleize %> Phone: <%= @job_inquiry.formated_phone_number %></p>

<p>
	<%= @job_inquiry.address_type.titleize %> Address: <br/>
	<%= @job_inquiry.line_1 %> <br/>
	<% if @job_inquiry.line_2.present? %>
	<%= @job_inquiry.line_2 %> <br/>
	<% end %>
	<% if @job_inquiry.line_3.present? %>
	<%= @job_inquiry.line_3 %> <br/>
	<% end %>
	<%= @job_inquiry.city %>, <%= @job_inquiry.region %> <%= @job_inquiry.zip %>
</p>

<% if @job_inquiry.comments.present? %>
<span>Comments: <br/></span>
<%= simple_format strip_tags(@job_inquiry.comments) %>
<% end %>

<p>
-----------------------------------------------------------------------<br/>
JSA Search, Inc. / 866-572-8326 / jsasearch.net <br/>
23120 Alicia Parkway Suite 110<br/>
Mission Viejo, CA 92692
</p>

app/views/employee_notifications/notify_job_request.html.erb
<p>-----------------------------------------------------------------------</p>
<p>You have received a job order request from <%= @job_request.name %>.</p>

<p>-----------------------------------------------------------------------</p>

<p>
	Name: <%= @job_request.try(:name) %>
</p>

<p>Title: <%= @job_request.title %></p>

<p>Company: <%= @job_request.company %></p>

<% if @user.present? %>
<p>
	<%= "#{@user.class.name.titleize}: " %>
	<%= link_to @user.name,
							send("#{@user.class.name.downcase}_url", @user),
							:title => "View Info" %>
</p>
<% end %>

<% if @facility.present? %>
<p>
	Facility: <%= link_to @facility.name,	client_url(@facility.client),	:title => "View Client Info of Facility" %>
</p>
<% end %>

<% if @contact.present? %>
<p>
	Contact: <%= link_to @contact.name,	client_contact_url(@contact.client, @contact), :title => "View Contact Info" %>
</p>
<% end %>

<p><%= @job_request.email_type.titleize %> Email: <%= @job_request.email_address %></p>

<p><%= @job_request.phone_type.titleize %> Phone: <%= @job_request.formated_phone_number %></p>

<p>
	<%= @job_request.address_type.titleize %> Address: <br/>
	<%= @job_request.line_1 %> <br/>
	<% if @job_request.line_2.present? %>
	<%= @job_request.line_2 %> <br/>
	<% end %>
	<% if @job_request.line_3.present? %>
	<%= @job_request.line_3 %> <br/>
	<% end %>
	<%= @job_request.city %>, <%= @job_request.region %> <%= @job_request.zip %>
</p>

<p>-----------------------------------------------------------------------</p>

<p>Job Order Title: <%= @job_request.job_title %></p>

<% if @job_request.comments.present? %>
<p>-----------------------------------------------------------------------</p>
<span>Comments: <br/></span>
<%= simple_format strip_tags(@job_request.comments) %>
<% end %>

<p>
-----------------------------------------------------------------------<br/>
JSA Search, Inc. / 866-572-8326 / jsasearch.net <br/>
23120 Alicia Parkway Suite 110<br/>
Mission Viejo, CA 92692
</p>

app/views/employee_notifications/notify_resume_submission.html.erb
<p>-----------------------------------------------------------------------</p>
<p>You have received a resume submission from <%= @resume_submission.name %>.</p>

<p>-----------------------------------------------------------------------</p>

<p>
	Name: <%= @resume_submission.try(:name) %>
</p>

<% if @candidate.present? %>
<p>
	Candidate: <%= link_to @candidate.name,
												 candidate_url(@candidate, :only_path => false),
												 :title => "Visit the candidate page" %>
</p>
<% end %>

<p><%= @resume_submission.email_type.titleize %> Email: <%= @resume_submission.email_address %></p>

<p>Title: <%= @resume_submission.try(:title) %></p>

<p>
	Company: <%= @resume_submission.try(:company) %>
</p>

<p><%= @resume_submission.phone_type.titleize %> Phone: <%= @resume_submission.formated_phone_number %></p>

<p>
	<%= @resume_submission.address_type.titleize %> Address: <br/>
	<%= @resume_submission.line_1 %> <br/>
	<% if @resume_submission.line_2.present? %>
	<%= @resume_submission.line_2 %> <br/>
	<% end %>
	<% if @resume_submission.line_3.present? %>
	<%= @resume_submission.line_3 %> <br/>
	<% end %>
	<%= @resume_submission.city %>, <%= @resume_submission.region %> <%= @resume_submission.zip %>
</p>

<% if @resume_submission.comments.present? %>
<span>Comments: <br/></span>
<%= simple_format strip_tags(@resume_submission.comments) %>
<% end %>

<p>
-----------------------------------------------------------------------<br/>
JSA Search, Inc. / 866-572-8326 / jsasearch.net <br/>
23120 Alicia Parkway Suite 110<br/>
Mission Viejo, CA 92692
</p>

app/views/employee_notifications/notify_signup.text.erb
Dear <%= @employee.name.split(" ").first %>,

<%= @person.name %> just signed up to be a <%= @person.class.name %>.

You can view their information at:
<%= @url %>

Check them out and give them a ring.

Thanks,
The Team at JSA Search, Inc.

------------------------------------------------------------
JSA Search, Inc. / 866-572-8326 / jsasearch.net
23120 Alicia Parkway Suite 110
Mission Viejo, CA 92692