config/routes.rb
require 'resque/server'

JSASearch::Application.routes.draw do
  
  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end
  
  authenticate :user do
    mount Resque::Server.new, :at => "/manage/resque1653508570"
  end
  
  scope "/manage" do
    resources :admin_defaults, :only => [:index, :edit, :update]

    resources :email_attachments, :only => [:create, :destroy]

    resources :clients do
      member do
        get :check_facility        
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
            
      resources :contacts
      
      resources :facilities do
        collection do
          get :tokens
        end
      end      
    end
    
    resource :facilities, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :contacts, :only => [] do
      collection do
        get :list
        put :mass_update
      end
    end

    resources :doc_templates

    resources :tasks do
      put :finish, :on => :member
    end

    resources :exports,         :only => [:index]
    resources :activities,      :only => [:index]
    
    resources :mass_messages,   :only => [:create]    
    resources :direct_messages, :only => [:new, :create]
    resources :quick_messages,  :only => [:new, :create]
    resources :share_files,     :only => [:new, :create]
    
    resources :import_items, :only => [:index, :create, :destroy]
        
    resources :attachments, :only => [:create, :destroy, :show, :edit, :update]
    
    resources :notes, :only => [:create, :destroy, :show]
    
    resources :employees do
      post :update_position, :on => :collection
    end
    
    resources :load_more, :only => [:index]
    
    resources :applicants, :only => [:create, :destroy, :update_status, :mass_create] do
      member do
        put :update_status
      end
      collection do
        post :mass_create
      end
    end

    resources :jobs do
      member do
        put :update_status
      end
      collection do
        post :edit_multiple
        put  :update_multiple
      end
    end
    
    resources :candidates do
      collection do
        post :edit_multiple
        put  :update_multiple
        get  :mass_email
      end
      resources :work_histories
      member do
        put :update_status
      end
      resources :resumes do
        get :generate, :on => :member
      end
    end
    
    resources :autocomplete, :only => [:clients, :jobs, :candidates, :zip_codes, :all] do
      collection do
        get :clients
        get :jobs
        get :candidates
        get :zip_codes
        get :all
      end
    end
    
    resources :tokens, :only => [:users, :users_with_email, :jobs, :contacts_with_email, :contacts, :us_states] do
      collection do
        get :users
        get :users_with_email
        get :jobs
        get :contacts        
        get :contacts_with_email
        get :us_states
      end
    end

  end

  resources :campaigns, :only => [:index]
  
  # resources :candidates,
  #           :only => [:new, :create],
  #           :controller => :public_candidates,
  #           :path_names => { :new => 'sign-up' },
  #           :as => 'public_candidates'
            
  # resources :clients,
  #           :only => [:new, :create],
  #           :controller => :public_clients,
  #           :path_names => { :new => 'sign-up'},
  #           :as => 'public_clients'
            
  resources :questions, :only => [:new, :create]
  resources :bios, :only => [:index, :show], :path => "executive-bios"

  resources :resume_submissions, :only => [:index, :new, :create], :path => 'resume-submissions'
  resources :job_requests, :only => [:index, :new, :create], :path => 'job-orders'

  match 'jobs' => 'public_jobs#index', :as => :public_jobs
  match 'jobs/:id' => 'public_jobs#show'
  resources :job_inquiries,
            :only => [:index, :new, :create],
            :path => 'jobs/:id/inquiries'
  
  match 'about' => "contents#about", :as => :about

  match 'newsletters' => "contents#newsletters", :as => :newsletters  
  
  match 'employers' => "contents#employers", :as => :employers
    match 'employers/healthcare' => "contents#healthcare", :as => :healthcare
    match 'employers/interim-staffing' => "contents#interim", :as => :interim_staffing
    match 'employers/consulting' => "contents#consulting", :as => :consulting
    match 'employers/finance-and-accounting' => "contents#finance", :as => :finance
    match 'employers/thanks' => "contents#client_thanks", :as => :client_thank_you
  
  match 'candidates' => "contents#candidates", :as => :about_candidates
    match 'candidates/career-advice' => "contents#advice", :as => :career_advice
    match 'candidates/resume-writing-services' => "contents#resume_services", :as => :resume_writing_services
    match 'candidates/thanks' => "contents#candidate_thanks", :as => :candidate_thank_you
  
  match 'contact' => "contents#contact", :as => :contact

  match 'manage/dashboard' => 'contents#dashboard'

  root :to => 'contents#home' 
  
end

app/views/shared/panels/_activity.html.haml
.c{"data-id" => activity.id, :class => activity_css_class(activity)}
  %hgroup
    %h1
      = link_to activity.author, employee_path(activity.author_id), :title => "View #{activity.author}'s info"
    %h2
      = l(activity.created_at.in_time_zone(current_time_zone),
          :format => :note_archive).downcase
  %p
    - if activity.deed_action == 3 && activity.deed_type != 7
      %span= "#{activity.display_deed_action} of"
      = link_to "#{activity.deed_name}", |
                {:controller => activity.display_deed_type.pluralize.downcase, :action => :show, :id => activity.deed_id }, |
                :title => "View info for #{activity.deed_name}" |
      %span= "to #{activity.try(:deed_parent).humanize}"

    - elsif activity.deed_action == 3 && activity.deed_type == 7
      %span= "#{activity.display_deed_action} of"
      = link_to "#{activity.deed_name}", |
                {:controller => :candidates, :action => :show, :id => activity.deed_id }, |
                :title => "View info for #{activity.deed_name}" |
      %span= "to #{activity.try(:deed_parent).humanize}"

    - elsif activity.deed_action == 4 && activity.deed_type == 6 
      %span= "#{activity.display_deed_action} about " 
      = link_to activity.deed_name, note_path(activity.deed_id), :title => "Read note", "data-remote" => "true"
      
    - elsif activity.deed_action == 5 && activity.deed_type == 6
      %span= "#{activity.display_deed_action} to "
      = link_to activity.deed_name, note_path(activity.deed_id), :title => "Read note", "data-remote" => "true"    
      
    - elsif activity.deed_action == 0 && activity.deed_type == 6 
      %span= "Added #{activity.display_deed_type.titleize} to" 
      = link_to activity.deed_name, note_path(activity.deed_id), :title => "Read note", "data-remote" => "true"
      
    - elsif activity.deed_type == 1 || activity.deed_type == 4  && activity.deed_action != 2
      %span= "#{activity.display_deed_action} #{activity.display_deed_type.titleize}:"
      = link_to activity.deed_name, {:controller => :clients, :action => :show, :id => activity.deed_id }, |
                :title => "View info for #{activity.deed_name}" |      

    - elsif activity.deed_action != 2 && activity.deed_type != 6 && activity.deed_type != 1
      %span= "#{activity.display_deed_action} #{activity.display_deed_type.titleize}:"
      = link_to activity.deed_name, {:controller => activity.display_deed_type.pluralize.downcase, :action => :show, :id => activity.deed_id }, |
                :title => "View info for #{activity.deed_name}" |      

    - else
      %span= "#{activity.display_deed_action} #{activity.display_deed_type.titleize}:"
      =  "#{activity.deed_name}"    

  - if activity.deed_action == 3 && activity.deed_parent.present?
    = content_tag(:span, activity.deed_parent, :class => "#{activity.deed_parent} state", :title => "#{activity.deed_parent.humanize}")

app/views/shared/panels/_applicant.html.haml
.c{"data-id" => applicant.id, :class => "#{applicant.current_state}"}
  .links          
    = link_to "Delete", applicant_path(applicant), :title => "Remove from Job Consideration", |
                        :class => "delete", |
                        "data-method" => 'delete',  |
                        "data-confirm" => "Are you Sure?", |
                        "data-remote" => "true" |                      
  %hgroup
    - if parent == "Candidate"
      %h1
        = link_to applicant.job.name, job_path(applicant.job), |
                  :title => "View #{applicant.job.name}'s info" |
                
      - if applicant.job.facility_ids.present? && applicant.job.facility_name.present?
        %h2
          = link_to applicant.job.facility_name, client_facility_path(applicant.job.client_id, applicant.job.facility_ids.first), |
                    :title => "View #{applicant.job.facility_name}'s info", |
                    :class => "preview", |
                    "data-remote" => "true" |
      - else
        %h2
          = link_to applicant.job.client_name, client_path(applicant.job.client_id), |
                    :title => "View #{applicant.job.client_name}'s info"

    - elsif parent == "Job"
      %h1
        = link_to applicant.candidate.name, candidate_path(applicant.candidate), |
                  :title => "View #{applicant.candidate.name}'s info" |                  
      %h2
        = applicant.candidate.display_title
        = content_tag(:em, "legacy title") if applicant.candidate.title.blank?
                

  %ul.states
    - DefaultVars::APPLICANT_TYPES.first(4).each do |state|
      %li
        = link_to state[:term].titleize, update_status_applicant_path(applicant, :new_status => state[:value].to_i), |
                 :class => current_state_class(state[:term], applicant), "data-remote" => "true", "data-method" => "put", |
                 :title => "Set as #{state[:term].titleize}" |
  %ul.states
    - DefaultVars::APPLICANT_TYPES[4..7].each do |state|
      %li 
        = link_to state[:term].titleize, update_status_applicant_path(applicant, :new_status => state[:value].to_i), |
                 :class => current_state_class(state[:term], applicant), "data-remote" => "true", "data-method" => "put", |
                 :title => "Set as #{state[:term].titleize}" |
  %ul.states
    - DefaultVars::APPLICANT_TYPES.last(5).each do |state|
      %li
        = link_to state[:term].titleize, update_status_applicant_path(applicant, :new_status => state[:value].to_i), |
                 :class => current_state_class(state[:term], applicant), "data-remote" => "true", "data-method" => "put", |
                 :title => "Set as #{state[:term].titleize}" |
                         
  = content_tag(:span, applicant.current_state, :class => "#{applicant.current_state} state", :title => "#{applicant.current_state}")

app/views/shared/panels/_attachment.html.haml
.c{"data-id" => "#{attachment.id}"}
  .links
    = link_to "Edit", edit_attachment_path(attachment.id, :file_parent_type => parent.class.name, :file_parent_id => parent.id), |
      :class => "edit", :title => "Edit"
    = link_to "Delete", attachment_path(attachment.id, :file_parent_type => parent.class.name, :file_parent_id => parent.id), |
                        :title => "Delete", |
                        :class => "delete", |
                        "data-method" => 'delete',  |
                        "data-confirm" => "Are you Sure?", |
                        "data-remote" => "true" |                      
  %hgroup
    %h1
      = attachment.name

  %p
    = link_to "Generate Download Link", attachment_path(attachment.id, :file_parent_type => parent.class.name, :file_parent_id => parent.id), |
              :title => "Download #{attachment.name}", :class => "button small", "data-remote" => "true" |
                            
  %p
    = link_to "Share File", |
              new_share_file_path(:parent_id => parent.id, |
                                  :parent_type => parent.class.name, |
                                  :shared_file_type => attachment.class.name, |
                                  :shared_file_id => attachment.id ), |
                                  :title => "Share #{attachment.name}", :class => "button small", "data-remote" => "true" |      
              

app/views/shared/panels/_candidate.html.haml
.c{"data-id" => candidate.id, :class => highlight_state(candidate.current_state)}
  .links          
    = link_to "Edit", edit_candidate_path(candidate), :class => "edit", :title => "Edit"
    - if admin?
      = link_to "Delete", candidate_path(candidate), :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |                      
  %hgroup
    %h1
      = link_to candidate.name, candidate_path(candidate), :title => "View #{candidate.name}'s info"
    %h2
      = candidate.display_title
      = content_tag(:em, "legacy title") if candidate.title.blank?

    %ul
      = render :partial => "shared/info/phone", :collection => candidate.phones.first(1)

      = render :partial => "shared/info/email_short", :collection => candidate.emails.first(1), :locals => {:parent => candidate}

      - candidate.addresses.first(1).each do |address|
        %li{:class => "#{address.type} adr"}
          %span{:class => "#{address.type} type"}= address.type
          = "#{address.city}, #{address.state}"        
      
        
  = content_tag(:span, candidate.current_state, :class => "#{candidate.current_state} state", :title => "#{candidate.current_state.titleize}")        

app/views/shared/panels/_client.html.haml
.c{"data-id" => client.id, :class => "#{client.current_state}"}
  .links          
    = link_to "Edit", edit_client_path(client), :class => "edit", :title => "Edit"
    - if admin?
      = link_to "Delete", client_path(client), :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |                      
  %hgroup
    %h1
      = link_to client.name, client_path(client), :title => "View #{client.name}'s info"

  - if client.emails.present? || client.phones.present?

    %ul
      = render :partial => "shared/info/phone", :collection => client.phones.first(1)

      = render :partial => "shared/info/email_short", :collection => client.emails.first(1), :locals => {:parent => client}
      
  = content_tag(:span, client.current_state, :class => "#{client.current_state} state", :title => "#{client.current_state.titleize}")
  

app/views/shared/panels/_contact.html.haml
- @facilities = client.facilities.where(:_id.in => contact.facility_ids).limit(2).only(:id, :name) unless contact.facility_ids.blank? 

.c{"data-id" => contact.id}
  .links          
    = link_to "Edit", edit_client_contact_path(client, contact), :class => "edit", :title => "Edit"
    - if admin?
      = link_to "Delete", client_contact_path(client, contact), :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |                      
  %hgroup
    %h1
      = link_to contact.name, client_contact_path(client, contact), :title => "Preview #{contact.name}'s info"
    %h2=contact.display_title
              
  - if contact.emails.present? || contact.phones.present?
          
    %ul
      = render :partial => "shared/info/phone", :collection => contact.phones.first(1)

      = render :partial => "shared/info/email_short", :collection => contact.emails.first(1), :locals => {:parent => contact}
  
  
  - if contact.facility_ids.present? && @facilities.present?         
    %p
      - @facilities.each do |facility|
        %span.tag
          = link_to facility.name, client_facility_path(client, facility.id), |
            :title => "View #{facility.name} info", |
            "data-remote" => "true" |

  %p= link_to "Preview info",
              client_contact_path(client, contact),
              :title =>  "View all of #{contact.name}'s info",
              "data-remote" => "true"

app/views/shared/panels/_facility.html.haml
- @contacts = client.contacts.where(:facility_ids => facility.id).limit(2).only(:id, :name, :title)

.c{"data-id" => facility.id}
  .links          
    = link_to "Edit", edit_client_facility_path(client, facility), :class => "edit", :title => "Edit"
    - if admin?
      = link_to "Delete", client_facility_path(client, facility), :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |                      
  %hgroup
    %h1
      = link_to facility.name, client_facility_path(client, facility), :title => "View #{facility.name}'s info", "data-remote" => "true"

  - if facility.emails.present? || facility.phones.present?

    %ul
      = render :partial => "shared/info/phone", :collection => facility.phones.first(1)

      = render :partial => "shared/info/email_short", :collection => facility.emails.first(1), :locals => {:parent => facility}

  - unless @contacts.blank?          
    %p
      - @contacts.each do |contact|
        %span.tag
          = link_to %Q[#{contact.name} - #{content_tag(:em, contact.display_title)}].html_safe, client_contact_path(client, contact.id), |
            :title => "View #{contact.name} info", |
            "data-remote" => "true" |

app/views/shared/panels/_job.html.haml
.c{"data-id" => job.id, :class => highlight_state(job.current_state)}
    
  .links          
    = link_to "Edit", edit_job_path(job), :class => "edit", :title => "Edit"
    - if admin?
      = link_to "Delete", job_path(job), :title => "Delete", |
                          :class => "delete", |
                          "data-method" => 'delete',  |
                          "data-confirm" => "Are you Sure?", |
                          "data-remote" => "true" |                      
  %hgroup
    %h1
      = link_to job.name, job_path(job), :title => "View #{job.name}'s info"
      
    - if job.facility_ids.present? && job.facility_names.present?
      %h2
        = link_to job.facility_name, client_facility_path(job.client_id, job.facility_ids.first), |
                  :title => "View #{job.facility_name}'s info", |
                  :class => "preview", |
                  "data-remote" => "true" |
    - else
      %h2= link_to job.client_name, client_path(job.client_id), :title => "View #{job.client_name}"
    %h2= "#{value_or_none(job.city_cache)}, #{value_or_none(job.region_cache)}" 

  %p= job.job_type
  
  = content_tag(:span, job.current_state, :class => "#{job.current_state} state", :title => "#{job.current_state.titleize}")

app/views/shared/panels/_resume.html.haml
.c{"data-id" => resume.id}
  .links          
    = link_to "Edit", edit_candidate_resume_path(candidate, resume), :class => "edit", :title => "Edit"
    = link_to "Delete", candidate_resume_path(candidate, resume), :title => "Delete", |
                        :class => "delete", |
                        "data-method" => 'delete',  |
                        "data-confirm" => "Are you Sure?", |
                        "data-remote" => "true" |
  %hgroup
    %h1
      = link_to resume.name, candidate_resume_path(candidate, resume), |
        :title => "View more info for #{resume.name}"
    %h2= truncate resume.objective
  
  - unless resume.generated_pdf.blank? || resume.currently_rendering?  
    %p 
      = link_to "Share PDF", |
                new_share_file_path(:parent_id => candidate.id, |
                                    :parent_type => candidate.class.name, |
                                    :shared_file_type => resume.class.name, |
                                    :shared_file_id => resume.id ), |
                                    :title => "Share #{resume.name}", :class => "button small ", "data-remote" => "true" |                                  
  - else
    %p 
      = link_to "Generate Resume", candidate_resume_path(candidate, resume), :class => "edit", :title => "Edit"                                  
    

app/views/shared/panels/_work_history.html.haml
.c{"data-id" => work_history.id}
  .links          
    = link_to "Edit", edit_candidate_work_history_path(candidate, work_history), :class => "edit", :title => "Edit"
    = link_to "Delete", candidate_work_history_path(candidate, work_history), :title => "Delete", |
                        :class => "delete", |
                        "data-method" => 'delete',  |
                        "data-confirm" => "Are you Sure?", |
                        "data-remote" => "true" |
  %hgroup
    %h1
      = link_to work_history.title, candidate_work_history_path(candidate, work_history), |
        :title => "View more info for #{work_history.title}", |
        "data-remote" => "true" |
    %h2= work_history.title
    %h3= work_history.company

  %p 
    %span= "#{work_history.started}"
    &#8211; 
    %span= "#{work_history.ended}"